# Change baseurl before deploy
baseurl = "https://alana.github.io"
locale  = "en-us"
title   = "Alana's Homelab"

defaultContentLanguage = "en"
hasCJKLanguage = false

[pagination]
    pagerSize = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'